### ISSUE TITLE
Write a little guidance text

### ISSUE THREAD

**Issue by AledLewis** [Fivium/FoxyDocs#13]
Hi,

I'm on the UK side of Fivium and I'm interested in finding out what FoxyDocs are all about. Could you add a little guidance on how to set-up?

Aled.

**Comment by ccameronmills** [comment]
I second this. Nick Palmer and myself would also be interested - have attempted to set something up but have been unsuccessful.

**Comment by Pierre-Do** [comment]
Done. A demo video is on the way.
